version: '2.3'
services:
  ForecastingConsumption:
    image: consumption:pred
    command: sh /root/start.sh
    ports:
      - "8080:8080"
    volumes:
      - $HOME/ForecastingElectricityConsumption/Data:/root/Data
      - $HOME/ForecastingElectricityConsumption/Code:/root/Code


