version: '2.3'
services:
  ForecastingConsumption:
    image: consumption:pred
    command: sh /root/start.sh
    ports:
      - "8080:8080"
    volumes:
      - /home/justo/ForecastingElectricityConsumption/Data:/root/Data


