version: '2.3'
services:
  PredictingConsumption:
    image: consumption:pred
    command: sh /root/start.sh
    ports:
      - "8080:8080"
    volumes:
      - $HOME/PredictingElectricityConsumption/Data:/root/Data
      - $HOME/PredictingElectricityConsumption/Code:/root/Code


